language: android
android:
  components:
    - build-tools-26.1.1
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - sys-img-armeabi-v7a-android-26
script:
- ./gradlew connectedAndroidTest