language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.1.1
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-26

script:
  - ./gradlew connectedAndroidTest