language: android

android:

  components:
    - build-tools-26.0.2
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26
    - sys-img-armeabi-v7a-android-26
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew connectedAndroidTest